apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pubsub
spec:
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: subscriber
        image: gcr.io/fukudak-gke/receiver:v1
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PROJECT
          value: fukudak-gke
        - name: PUBSUB_TOPIC
          value: echo
        - name: PUBSUB_SUBSCRIPTION
          value: echo-read
  

